### ISSUE TITLE
Starting project

### ISSUE THREAD

**Issue by CM-CA** [CM-CA/HacktoberFest-2k9#4]
Starting project of bike store using Vue and Django tecnologies

**Comment by BalSharma** [comment]
I do not about Django but if you permit I can start using Vue?

**Comment by BalSharma** [comment]
I have started working on VueJs bike store project. FYI . Thank you.

**Comment by CM-CA** [comment]
Sure @BalSharma  you can start with us, its a open-source project to learn :)
